name: pytest

on:
  push:
  pull_request:

jobs:

  base:
    name: Prepare dependencies
    runs-on: ubuntu-20.04
    needs: info
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.2
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.2
        with:
          repository: home-assistant/core
          path: homeassistant
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e homeassistant/
      - name: Run pytest
        timeout-minutes: 60
        run: |
          pytest tests
