name: pytest

on:
  push:
    branches: [master]
  pull_request:

jobs:

  pytest:
    name: Prepare dependencies
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.2
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.2
        with:
          repository: home-assistant/core
          path: homeassistant
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade pytest
          pip install -r homeassistant/requirements_test.txt
          pip install -e homeassistant/
      - name: Run pytest
        timeout-minutes: 60
        run: |
          PYTHONPATH=${PYTHONPATH}:custom_components/:homeassistant/tests pytest tests
